v0.10.0
qytiz/qna pull request #10
Opened 2021-03-30 11:28 UTC by qytiz

2021-03-30 16:06 UTC, vkurennov requested changes

2021-03-30 16:06 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    answer.destroy if can?(:destroy, answer)
вот это все как раз неверно. в контроллере мы вызываем либо метод authorize! внутри экшенов, либо authorize_recource на уровне всего контроллера, а методы can?  - это всего лишь хелперы для видов (ну можно их не только в видах использовать, но на практике этого никто не делает). в общем, пересмотр урок еще раз

2021-03-30 16:06 UTC, vkurennov commented on app/controllers/application_controller.rb
>  class ApplicationController < ActionController::Base
следует включить проверку авторизации для всех контроллеров

2021-03-30 16:06 UTC, vkurennov commented on app/controllers/application_controller.rb
> +  rescue_from CanCan::AccessDenied do |exception|
у тебя обработчик только для обычных запросов, а для js  и json стоит возвращать статус forbidden (403) и уже на клиенте его обрабатывать

2021-03-30 16:06 UTC, vkurennov commented on app/models/ability.rb
> +    can [:upvote, :downvote, :delete_vote], Answer do |answer|
1) почему правила голосования только для ответа? за вопрос у нас тоже можно голосовать
2) для удаления голоса как раз обратное правило: его удалить может только тот, кто его создал

2021-03-31 08:31 UTC, vkurennov requested changes

2021-03-31 08:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  authorize_resource
либо `authorize_resource`, либо` authorize!` в экшенах, но не одновременно, потому что метод `authorize_resource` как раз и вызывает `authorize!` перед каждым экшеном. фактически, сейчас ты дважды выполняешь авторизацию каждого экшена, не страшно, но зачем это делать дважды?

2021-03-31 08:31 UTC, vkurennov commented on app/controllers/application_controller.rb
> +  check_authorization unless: :devise_controller?
т.к. это глобальный фильтр, стоит его указать там же, где остальные before_action, т.е. в начале

2021-03-31 08:31 UTC, vkurennov commented on app/controllers/application_controller.rb
> +      format.js { head :forbidden, content_type: 'text/html' }
зачем переписывать  content_type? запрос пришел в js, пусть и овтет будет в том же формате

2021-03-31 08:31 UTC, vkurennov commented on app/controllers/comments_controller.rb
> +    authorize! :create, Comment
опять двойная авторизация

2021-03-31 08:31 UTC, vkurennov commented on app/controllers/concerns/voted.rb
>  module Voted
а вот тут как раз нужно авторизацию вызывать внутри экшенов, потому что надо правильный объект передать

2021-03-31 08:31 UTC, vkurennov commented on app/controllers/files_controller.rb
> +  skip_authorization_check
зачем тут делать skip и потом все равно вызывать авторизацию?

2021-03-31 08:31 UTC, vkurennov commented on app/controllers/links_controller.rb
> +  authorize_resource
лишняя авторизация

2021-03-31 08:31 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  authorize_resource
я понял, почему у тебя не работает этот хелпер: потому что у тебя объект не загружается через before_action, а через метод в момент его вызова. ок, тогда просто убери этот хелпер и вызывай везде `authorize!`

2021-03-31 08:31 UTC, vkurennov commented on app/controllers/users_controller.rb
>  class UsersController < ApplicationController
а зачем вообще этот контроллер, если он ничего не делает?

2021-03-31 08:31 UTC, vkurennov commented on app/models/ability.rb
> +    can [:upvote, :downvote], Answer, Question do |votable|
а теперь посмотри на несколько строк выше и заметь, как перечисляютс несколько объектов, на которые написано правило - они в массиве.

2021-03-31 08:31 UTC, vkurennov commented on app/models/ability.rb
> +    can [:delete_vote], Vote do |vote|
а у тебя точно есть такой экшн где-либо?

2021-03-31 10:58 UTC, qytiz commented on app/controllers/questions_controller.rb
> +  authorize_resource
Тогда мне пришлось бы убрать check_authorization или добавить  skip_authorization_check я просто вызову  перед нужными экшенами хелпер, мне кажется это будет более верно с точки зрения руби

2021-04-01 09:34 UTC, vkurennov requested changes

2021-04-01 09:34 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  authorize_resource
нет, все же надо вызвыать authorize! в контроллерах, а не authorize_resource, потому что у тебя объект не загружен до вызова этого метода (он загружается уже после), иначе у тебя неверно будут правила работать, не будут учитываться дополнительные условия авторизации (типа проверки на автора). `authorize_resource` работает так: если на момент его вызова загружен объект одноименный контроллеру (для AnswersController это @answer), то вызывается метод `authorize!` и ему передается  имя экшена и этот объект, если он не загружен, то передается только название класса, в этом случае, все дополнителные условия в Ability игнорируются.

это касается всех контроллеров

P.S. и `check_authorization` работает и с authorize!, он по сути просто проверяет, чтобы при каждом вызове экшена был вызван метод `authorize!`

2021-04-01 09:34 UTC, vkurennov commented on app/controllers/application_controller.rb
> +      format.js { head :forbidden, content_type: 'text/html' }
ну и? где исправление [этого комментария](https://github.com/qytiz/qna/pull/10/files#r604696282)?

2021-04-01 09:34 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  authorize_resource
нет, не пришлось бы, как выше написал,  `check_authorization` лишь проверяет вызов `authorize! `внутри каждого экшена

2021-04-01 09:34 UTC, vkurennov commented on app/models/ability.rb
> +    can [:delete_vote], Vote do |vote|
к чему относится это правило? Где у тебя экшн `delete_vote`?

2021-04-01 10:00 UTC, qytiz commented on app/controllers/answers_controller.rb
> +  authorize_resource
Моя проблема была в  геме, видимо он как-то криво встал, я его переустановил и все начало работать

2021-04-02 08:07 UTC, vkurennov approved these changes

2021-04-03 07:53 UTC, merged