v0.8.0
qytiz/qna pull request #8
Opened 2021-03-22 20:20 UTC by qytiz

2021-03-23 07:08 UTC, vkurennov requested changes

2021-03-23 07:08 UTC, vkurennov commented on app/models/vote.rb
> +    vote.score += 1
но это изменит значение лишь в памяти, в базе-то не сохранится, нужно save вызывать, чтобы в базе сохранить значения

2021-03-23 07:08 UTC, vkurennov commented on app/models/vote.rb
> +    vote.score -= 1
и тут то же самое

2021-03-23 07:08 UTC, vkurennov commented on app/models/vote.rb
> +    nil
зачем nil возвращать?

2021-03-23 07:08 UTC, vkurennov commented on app/models/vote.rb
> +  def self.upvote(user, votable)
не очень мне нравится большое кол-во методов класса, это ведь действия над каким-то объектом, лучше вынести их в консерн моделей и вызывать у вопроса/ответа

2021-03-23 07:08 UTC, vkurennov commented on spec/features/answer/vote_spec.rb
> +    scenario 'can upvote' do
добавь в этот и следующий сценарий еще такие шаги после текущих проверок: снова заходим на ту же страницу и снова проверяем, что рейтинг равен 1 (и в след тесте -1), это чтобы выявить баг с несохранением голоса.

2021-03-23 07:08 UTC, vkurennov commented on app/models/vote.rb
> +class Vote < ApplicationRecord
а где тесты на все эти методы?

2021-03-23 07:08 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +module Voted
где тесты контроллеров на эти экшены?

2021-03-23 08:43 UTC, qytiz commented on app/models/vote.rb
> +    vote.score += 1
Save у меня вызвается в concern у контроллера,  что-бы вернуть либо ошибку либо объект vote

2021-03-23 08:43 UTC, qytiz commented on app/models/vote.rb
> +    vote.score -= 1
Save у меня вызвается в concern у контроллера, что-бы вернуть либо ошибку либо объект vote

2021-03-23 08:45 UTC, qytiz commented on app/models/vote.rb
> +    nil
без него выкидывает ошибку и мне не удалось иначе это решить

2021-03-24 06:41 UTC, vkurennov commented on app/models/vote.rb
> +    vote.score += 1
ну и зря, потому что метод должен работу сделать полностью, иначе у тебя получается, что надо всегда вызывать этот метод + save, что как бы и намекает на то, что это просто последняя инструкция алгоритма и она должна быть инкапсулирована в метод вместе с остальными шагами

2021-03-24 06:46 UTC, vkurennov requested changes

2021-03-24 06:46 UTC, vkurennov commented on app/models/vote.rb
> +    nil
какую ошибку? "не удалось решить и возвращаю nil" - это костыль, а не решение.

2021-03-24 06:46 UTC, vkurennov commented on spec/features/answer/create_from_question_spec.rb
> +    # scenario 'attach file' do
почему для аттачментов закомментировал сценарий? не проходит? разберись и добейся, чтобы проходил

2021-03-24 06:46 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +module Voted
тесты на экшены из консерна так и не написаны

2021-03-24 06:46 UTC, vkurennov commented on spec/concerns/votes_spec.rb
> +RSpec.describe Voted do
у тебя еще метод total_score есть, его тоже надо тестировать

2021-03-24 06:46 UTC, vkurennov commented on spec/concerns/votes_spec.rb
> +  it { expect(answer.upvote(user).score).to eq 1 }
у тебя логика чуть сложнее для каждого метода. например, у тебя удаляется голос, если он уже есть, это надо тоже тестировать. вообще, в тестах надо все поведение метода проверять, а не только основное

2021-03-24 10:10 UTC, qytiz commented on spec/concerns/votes_spec.rb
> +  it { expect(answer.upvote(user).score).to eq 1 }
Этот метод я тестировал внутри модели поскольку описан он там

2021-03-24 14:40 UTC, vkurennov requested changes

2021-03-24 14:40 UTC, vkurennov commented on app/models/concerns/votable.rb
> +  def upvote(user)
Я тебе ответом на предыдущий твой коммент написал:

> зря save делаешь в контроллере, потому что метод должен работу сделать полностью, иначе у тебя получается, что надо всегда 
вызывать этот метод + save, что как бы и намекает на то, что это просто последняя инструкция алгоритма и она должна быть инкапсулирована в метод вместе с остальными шагами

2021-03-24 15:23 UTC, qytiz commented on app/models/concerns/votable.rb
> +  def upvote(user)
Кхм, не увидел прошу прощения, исправил и прогнал ещё раз все тесты

2021-03-25 07:35 UTC, vkurennov requested changes

2021-03-25 07:35 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +        if vote == true
не надо сравнивать с true, если в переменной уже лежит булеан-значение. если написать просто `if vote`  будет то же самое (проведи мысленный эксперимент с подставлением разных значений в переменную).
А еще лучше сам вызов метода перенести в условие, как мы с save в контроллерах обычно делаем.

2021-03-25 07:35 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +        if vote == true
тут то же самое

2021-03-25 07:35 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    respond_to do |format|
вот эта часть полностью дублируется, можно вынести ее в приватный метод контроллера и вызывать из экшенов

2021-03-25 07:35 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +        if vote == true
а, я понял, почему тебе приходится сравнивать с true, потому что у тебя либо объект возвращается, либо результат save, но это не очень хорошо, лучше сделать так, чтобы возвращался либо true либо false (в крайнем случае - nil), тогда у тебя будет более ожидаемое поведение метода. А еще лучше вариант - возвращать объект голоса в случае успеха и nil в случае неудачи

2021-03-25 07:35 UTC, vkurennov commented on app/models/concerns/votable.rb
> +  def upvote(user)
отрефактори этот и следующий метод так, чтобы в случае успеха он возвращал созданный голос, а в случае неудачи - nil

2021-03-25 07:35 UTC, vkurennov commented on app/models/concerns/votable.rb
> +  def downvote(user)
у тебя методы отличаются только знаком голоса. можно вынести все это в приватный метод и передавть туда лишь параметр +/-1 (подсказка `vote.score += -1` это то же самое, что `vote.score -= 1`)

2021-03-25 07:35 UTC, vkurennov commented on app/models/vote.rb
> +  validates :score, inclusion: { in: [-1, 0, 1], message: 'No double votes!' }
а зачем нулевой голос? нет смысла хранить нули, их нужно удалять

2021-03-25 07:35 UTC, vkurennov commented on spec/concerns/votable_spec.rb
> +  it do
в  it нужно описание ставить, чтобы была как бы документация, что проверяет этот метод

2021-03-25 07:35 UTC, vkurennov commented on spec/concerns/votable_spec.rb
> +  it do
пустые строки между методами, тестами и др. блоками кода!

2021-03-25 07:35 UTC, vkurennov commented on spec/concerns/votable_spec.rb
> +    create_list(:vote, 5, user: create(:user), score: 1, votable: answer)
тут лучше создать несколько положительных, отрицательных и затем проверить общий рейтинг

2021-03-25 12:13 UTC, qytiz commented on app/controllers/concerns/voted.rb
> +        if vote == true
К сожалению в данном случае при возврате nil или false будет возникать проблема с рендером ошибок, потому для более предсказуемого поведения и использую проверку vote.errors.empty? и всегда возвращать объект из метода

2021-03-25 16:41 UTC, vkurennov approved these changes

2021-03-26 09:10 UTC, merged